on:
  push:
    branches:
      - master
jobs:
  foo:
    runs-on: windows-latest
    steps:
      - run: pwd
      - run: whoami
      - run: Get-ADPrincipalGroupMembership -Identity $env:UserName